fix usage of varargs in ScKeynodes
ostis-ai/py-sc-client pull request #11
Opened 2022-06-29 10:41 UTC by DBrutski

2022-06-29 10:49 UTC, NikitaZotov approved these changes

2022-06-29 10:53 UTC, MikhailSadovsky approved these changes

2022-06-29 10:54 UTC, AlexandrZagorskiy commented on tests/api_test.py
> +    def test_should_get_keynode(self):
If I will use an incorrect identifier, what should ScKeynodes class return? Can you add one more test for such situation?

2022-06-29 11:14 UTC, AlexandrZagorskiy requested changes

2022-06-29 11:14 UTC, AlexandrZagorskiy commented on tests/api_test.py
>      TestClientCheckElements,
CI was failed, please fix errors

2022-07-05 09:19 UTC, DBrutski commented on tests/api_test.py
> +    def test_should_get_keynode(self):
done

2022-07-05 09:20 UTC, DBrutski commented on tests/api_test.py
>      TestClientCheckElements,
fixed

2022-07-06 13:06 UTC, AlexandrZagorskiy approved these changes

2022-07-06 13:06 UTC, AlexandrZagorskiy commented on README.md
>  *Parameters*: An ScAddr class object.
```suggestion
*Parameters*: ScAddr class objects.
```

2022-07-06 13:06 UTC, merged