Feature/client implementation
ostis-ai/py-sc-client pull request #2
Opened 2022-05-06 09:21 UTC by AlexandrZagorskiy

2022-05-09 12:32 UTC, MikhailSadovsky requested changes

2022-05-09 12:32 UTC, MikhailSadovsky commented on .github/workflows/pull-request-CI.yml
> +          error: "One of commit messages has an incorrect title. Please read the documentation: docs/dev/pr.md"
We haven't link `docs/dev/pr.md` in repo. Could you please refer to existing link?

2022-05-09 12:32 UTC, MikhailSadovsky commented on src/sc_client/client/__init__.py
>  """
Question regarding project structure: is it ok to have sc_client/client folders inside py-sc-client project?

2022-05-09 12:32 UTC, MikhailSadovsky commented on tox.ini
> +[tox]
Could you please update README with info how to install lib

2022-05-11 09:51 UTC, Vikort commented on .github/workflows/push-CI.yml
> +        black --diff --color --line-length 120 src
with `diff` flag black return 0 code even if files need to be reformatted, use `check` argument instead

2022-05-11 09:51 UTC, Vikort commented on src/sc_client/constants/common.py
>  BINARY = "binary"
Why this constants not in `Enum` classes? Why some classes with constants are Enum and others are not?

2022-05-11 09:51 UTC, Vikort commented on .github/workflows/run-tests.yml
> +    - run: pip install tox
Why install `tox` if it installed from `requirements-dev.txt`?

2022-05-12 11:18 UTC, AlexandrZagorskiy commented on src/sc_client/client/__init__.py
>  """
Why not ? I didn't see any problems with such naming and structure. Also it looks good for import:
`from sc_client import client`
I admit that project can be restructured, there can be some shortcomings, the reason is just a lack of experience

2022-05-12 11:57 UTC, AlexandrZagorskiy commented on src/sc_client/constants/common.py
>  BINARY = "binary"
I used Enum mostly for parts of code when I need to use both keys and values. I think there is no need to move every constant to class and inherit it from Enum.

2022-05-12 16:02 UTC, Vikort approved these changes

2022-05-13 08:51 UTC, MikhailSadovsky requested changes

2022-05-13 08:51 UTC, MikhailSadovsky commented on docs/dev/git-workflow.md
> +## Installation
Please move to separate installation doc file

2022-05-13 08:51 UTC, MikhailSadovsky commented on docs/dev/git-workflow.md
> +This project uses [Git-Flow](https://www.gitkraken.com/learn/git/git-flow),
Please add info about fork creation

2022-05-13 09:56 UTC, MikhailSadovsky requested changes

2022-05-13 09:56 UTC, MikhailSadovsky commented on .github/workflows/run-tests.yml
> +name: Tests
Please fix CI issues and add CI badge to README

2022-05-13 13:30 UTC, MikhailSadovsky approved these changes

2022-05-13 13:43 UTC, merged