Handling exceptions: providing invalid arguments for client API
ostis-ai/py-sc-client pull request #26
Opened 2022-08-29 07:35 UTC by AlexandrZagorskiy

2022-08-29 08:09 UTC, FalseR20 approved these changes

2022-08-29 13:15 UTC, FallenChromium commented
This PR was a result of having a hard-to-trace bug, and the problem being the wrong argument for the API method. There could be more cornercases like this though, wouldn't it be better to have a 100% method to check if the method was successful? The `status` field returned from the API will probably suffice, but there isn't a way to check for it right now. Alternatively we could throw an exception if status is 0, sounds a bit weird to me though.

2022-09-02 07:13 UTC, FalseR20 approved these changes

2022-09-02 09:25 UTC, AlexandrZagorskiy commented
> This PR was a result of having a hard-to-trace bug, and the problem being the wrong argument for the API method. There could be more cornercases like this though, wouldn't it be better to have a 100% method to check if the method was successful? The `status` field returned from the API will probably suffice, but there isn't a way to check for it right now. Alternatively we could throw an exception if status is 0, sounds a bit weird to me though.

The _status_ field does not always represent that server returned error. Nikita mention it [here](https://github.com/ostis-ai/sc-machine/pull/137#discussion_r957826228). Returning status 0 without content means that command finished unsuccessfully, but in most cases, I think, this is a result of the wrong request from the user side, like a case with creating an empty list of the elements. You think that users should have access to the _status_ field, and it should be implemented? I think that raising errors is enough.

2022-09-02 20:15 UTC, NikitaZotov requested changes

2022-09-02 20:15 UTC, NikitaZotov commented on src/sc_client/client/_payload_factory.py
> +        if not isinstance(constr, ScConstruction):
Not all command cause exceptions

2022-09-02 20:15 UTC, NikitaZotov commented on src/sc_client/client/_payload_factory.py
> +            raise exceptions.InvalidTypeError("expected object types: ScConstruction")
Fix all errors catching in corresponding with logic in sc-server

2022-09-12 19:34 UTC, NikitaZotov approved these changes

2022-09-12 19:34 UTC, merged