refactor: clarify all sc-client names
ostis-ai/py-sc-client pull request #59
Opened 2024-09-23 14:16 UTC by NikitaZotov

2024-09-26 11:55 UTC, KovalM approved these changes

2024-09-27 09:01 UTC, kilativ-dotcom requested changes

2024-09-27 09:01 UTC, kilativ-dotcom commented on README.md
> +# Triple `question_node-(*new)connector_access-(*aliased with "_action_node")action_node`
membership instead of connector

2024-09-27 09:01 UTC, kilativ-dotcom commented on README.md
> +- *sc_client.client*.**get_element_types**(*addrs: ScAddr)
element types looks like element has a lot of types

2024-09-27 09:01 UTC, kilativ-dotcom commented on README.md
>  ### Get links contents by content substring
shouldn't these headers change accordingly to method names?

2024-09-27 09:01 UTC, kilativ-dotcom commented on README.md
> -class MyAgent(ScAgent):
why were agents removed?

2024-09-27 09:01 UTC, kilativ-dotcom commented on docs/changelog.md
> + - `ScEvent` class was renamed to `ScEventSubscription`, `ScEventParams` class was renamed to `ScEventSubscriptionParams`, and sc-event types in `ScEventType` were changed according the table below.
```suggestion
 - `ScEvent` class was renamed to `ScEventSubscription`, `ScEventParams` class was renamed to `ScEventSubscriptionParams`, and sc-event types in `ScEventType` were changed according to the table below.
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on docs/changelog.md
> + - This version is compatible with version of the sc-machine 0.10.0. All API methods were redesigned. Misleading ones were removed, new ones were added. See table below, to learn more about changes.
don't use 'misleading'

2024-09-27 09:01 UTC, kilativ-dotcom commented on docs/changelog.md
> +  | ADD_INGOING_EDGE       | AFTER_GENERATE_INGOING_ARC  |
```suggestion
  | ADD_INGOING_EDGE       | AFTER_GENERATE_INCOMING_ARC  |
```
fix everywhere

2024-09-27 09:01 UTC, kilativ-dotcom commented on docs/changelog.md
> + - ScClient methods: `get_element_types`, `generate_elements`, `generate_node`, `generate_link`, `generate_connector`, `generate_elements_by_scs`, `erase_elements`, `search_links_by_contents`, `searc
quintuple is method for template, not client

2024-09-27 09:01 UTC, kilativ-dotcom commented on docs/changelog.md
> + - Deprecated `ScAgent` and `ScModule` classes
items of 'removed' section start with 'deprecated'
deprecated items should be in separate section and without 'deprecated'

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_api.py
> +        "ScClient 'get_links_by_content' method is deprecated. Use `erase_elements` method instead.", DeprecationWarning
```suggestion
        "ScClient 'get_links_by_content' method is deprecated. Use `search_links_by_content` method instead.", DeprecationWarning
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_payload_factory.py
> +        common.ClientCommand.GET_ELEMENT_TYPES: CheckElementsPayloadCreator(),
```suggestion
        common.ClientCommand.GET_ELEMENTS_TYPES: GetElementsTypesPayloadCreator(),
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_payload_factory.py
> +        common.ClientCommand.SEARCH_LINKS_CONTENTS_BY_CONTENT_SUBSTRING: SearchLinksByContentSubstringPayloadCreator(),
```suggestion
        common.ClientCommand.SEARCH_LINKS_CONTENTS_BY_CONTENT_SUBSTRING: SearchLinksContentsByContentSubstringPayloadCreator(),
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_response_processor.py
> +    def __call__(self, response: Response, *events: ScEventSubscription) -> list[ScEventSubscription]:
```suggestion
    def __call__(self, response: Response, *event_subscriptions: ScEventSubscription) -> list[ScEventSubscription]:
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_response_processor.py
> +            sc_event = ScEventSubscription(command_id, event.event_type, event.callback)
```suggestion
            sc_event_subscription = ScEventSubscription(command_id, event.event_type, event.callback)
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_response_processor.py
>          for count, event in enumerate(events):
```suggestion
        for count, event_subscription in enumerate(events):
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_response_processor.py
> +    def __call__(self, response: Response, *events: ScEventSubscription) -> bool:
```suggestion
    def __call__(self, response: Response, *event_subscriptions: ScEventSubscription) -> bool:
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/client/_response_processor.py
> +        c.ClientCommand.GET_ELEMENT_TYPES: CheckElementsResponseProcessor(),
```suggestion
        c.ClientCommand.GET_ELEMENTS_TYPES: GetElementsTypesResponseProcessor(),
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on src/sc_client/models/sc_construction.py
> +            "ScConstruction 'create_edge' method is deprecated. Use `generate_connector` method instead.",
```suggestion
            "ScConstruction 'create_node' method is deprecated. Use `generate_node` method instead.",
```

2024-09-27 09:01 UTC, kilativ-dotcom commented on docs/changelog.md
> + - Deprecated `ScAgent` and `ScModule` classes
turns out 'deprecated' here meant that they were deprecated previously and removed now
that's what misleading means

2024-09-29 15:00 UTC, NikitaZotov commented on README.md
> -class MyAgent(ScAgent):
There are in sc-kpm. These ones are deprecated

2024-09-29 15:03 UTC, NikitaZotov commented on docs/changelog.md
> + - Deprecated `ScAgent` and `ScModule` classes
Yes

2024-09-29 15:04 UTC, NikitaZotov commented on src/sc_client/client/_payload_factory.py
> +        common.ClientCommand.GET_ELEMENT_TYPES: CheckElementsPayloadCreator(),
This is incorrect in terms of the English language

2024-09-29 15:10 UTC, NikitaZotov commented on README.md
> +- *sc_client.client*.**get_element_types**(*addrs: ScAddr)
get_elements_types is incorrect

2024-09-30 08:05 UTC, kilativ-dotcom commented on README.md
>  ### Get links contents by content substring
not all were changed

2024-09-30 08:07 UTC, kilativ-dotcom commented on docs/changelog.md
> +  | ADD_INGOING_EDGE       | AFTER_GENERATE_INGOING_ARC  |
not everywhere was fixed

2024-09-30 08:12 UTC, kilativ-dotcom commented on src/sc_client/client/_response_processor.py
> +            event_subscription = ScEventSubscription(
event_subscription is used for different variables

2024-10-01 08:47 UTC, NikitaZotov commented on src/sc_client/client/_response_processor.py
> +        c.ClientCommand.GET_ELEMENT_TYPES: CheckElementsResponseProcessor(),
Okay

2024-10-01 08:48 UTC, NikitaZotov commented on src/sc_client/client/_payload_factory.py
> +        common.ClientCommand.GET_ELEMENT_TYPES: CheckElementsPayloadCreator(),
Okay

2024-10-01 08:53 UTC, NikitaZotov commented on README.md
>  ### Get links contents by content substring
Where?

2024-10-01 08:54 UTC, NikitaZotov commented on README.md
> +- *sc_client.client*.**get_element_types**(*addrs: ScAddr)
Okay

2024-10-01 12:57 UTC, kilativ-dotcom commented on README.md
remove warning
Warning: there are some of these classes in py-sc-client (deprecated)

2024-10-01 12:57 UTC, kilativ-dotcom commented on README.md
> -  Run function with each triple. Deprecated in version 0.3.0
same deprecation is for ScTemplateResult.size()

2024-10-01 12:57 UTC, kilativ-dotcom commented on README.md
>  ### Get links contents by content substring
Search template
Generate template
Check element types
Create elements by SCS
Delete elements

2024-10-01 13:03 UTC, kilativ-dotcom approved these changes

2024-10-01 13:03 UTC, kilativ-dotcom commented on docs/changelog.md
> + - sc-event types: `AFTER_GENERATE_CONNECTOR`, `AFTER_GENERATE_OUTGOING_ARC`, `AFTER_GENERATE_INCOMING_ARC`, `AFTER_GENERATE_EDGE`, `BEFORE_ERASE_CONNECTOR`, `BEFORE_ERASE_OUTGOING_ARC`, `BEFORE_ERAS
ingoing arc here

2024-10-04 13:44 UTC, merged